version: 2

jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Install git
          command: |
            apt-get update
            apt-get install -y git
      - run:
          name: Building
          command: ./build.sh
