version: 2

jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y avr-libc avrdude binutils-arm-none-eabi binutils-avr build-essential dfu-programmer dfu-util gcc gcc-avr git libnewlib-arm-none-eabi software-properties-common unzip wget zip
      - run:
          name: Building
          command: ./build.sh
